"""initial_schema

Revision ID: 09dda5efec81
Revises: 
Create Date: 2026-04-07 13:44:05.842447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dda5efec81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('min_players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('small_blind', sa.Integer(), nullable=False),
    sa.Column('big_blind', sa.Integer(), nullable=False),
    sa.Column('allow_rebuy', sa.Boolean(), nullable=False),
    sa.Column('rebuy_amount', sa.Integer(), nullable=True),
    sa.Column('starting_chips', sa.Integer(), nullable=False),
    sa.Column('dealer_seat', sa.Integer(), nullable=True),
    sa.Column('current_street', sa.String(length=16), nullable=True),
    sa.Column('pot', sa.Integer(), nullable=False),
    sa.Column('community_cards', sa.Text(), nullable=False),
    sa.Column('deck_state', sa.Text(), nullable=False),
    sa.Column('current_player_id', sa.String(length=36), nullable=True),
    sa.Column('aggressor_player_id', sa.String(length=36), nullable=True),
    sa.Column('hand_number', sa.Integer(), nullable=False),
    sa.Column('last_raise_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['aggressor_player_id'], ['players.id'], name='fk_game_aggressor', use_alter=True),
    sa.ForeignKeyConstraint(['current_player_id'], ['players.id'], name='fk_game_current_player', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('chips', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('bet_this_street', sa.Integer(), nullable=False),
    sa.Column('total_bet_this_hand', sa.Integer(), nullable=False),
    sa.Column('hole_cards', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_token'), ['token'], unique=True)

    op.create_table('side_pots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('hand_number', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('cap', sa.Integer(), nullable=True),
    sa.Column('eligible_player_ids', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('hand_number', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=16), nullable=False),
    sa.Column('action_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index('ix_actions_game_hand_seq', ['game_id', 'hand_number', 'sequence'], unique=False)

    op.create_table('hand_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(length=36), nullable=False),
    sa.Column('hand_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('hole_cards', sa.Text(), nullable=False),
    sa.Column('best_hand', sa.Text(), nullable=True),
    sa.Column('hand_rank', sa.Integer(), nullable=True),
    sa.Column('hand_description', sa.String(length=128), nullable=True),
    sa.Column('pot_won', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hand_results')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index('ix_actions_game_hand_seq')

    op.drop_table('actions')
    op.drop_table('side_pots')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_token'))

    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
